```python
from typing import List

def sort_numbers(numbers: str) -> str:
    """ Input is a space-delimited string of numbers from 'zero' to 'nine'.
    Valid choices are 'zero', 'one', 'two', 'three', 'four', 'five', 'six', 'seven', 'eight' and 'nine'.
    numbers = [int(num) for num in numbers.
    return f'numbers generated by sorting numbers from smallest to largest
    """
    return f"{numbers[0]} {numbers[1]} {numbers[2]}..."

# test the function
test_str = "three one five"
sorted_str = sort_numbers(test_str)
print(sorted_str) # expected output: one three five
```