```python
from typing import List
from itertools import dropwhile


def all_prefixes(string: str) -> List[str]:
    """ Return list of all prefixes from shortest to longest of the input string """
    return list(reversed(list(dropwhile(lambda x: x != '', string))))}
```
This code reverses the list generated by the `dropwhile` function, which removes elements from the beginning of the string for as long as the element is not empty. The `dropwhile` function stops removing elements when the first non-empty element is encountered, ensuring that the shortest prefix is the first element in the list.