```python
from typing import List
from itertools import dropwhile


def all_prefixes(string: str) -> List[str]:
    """ Return list of all prefixes from shortest to longest of the input string """
    return list(reversed(list(dropwhile(lambda x: x != '', string))))}
```
This code reverses the list generated by the `itertools.dropwhile` function, which sequentially drops elements from the given iterable as long as the predicate returns `True`. By dropping elements as long as the string portion is not empty, we obtain a reversed list of prefixes from the input string.