```python
from typing import List
from itertools import dropwhile


def all_prefixes(string: str) -> List[str]:
    """ Return list of all prefixes from shortest to longest of the input string """
    return list(reversed(list(dropwhile(lambda x: len(x) > 0, string))));
```
The above code reverses the list generated by the `dropwhile` function so that the longest prefix is at the first element of the list, and the shortest prefix is at the last element. The `dropwhile` function filters elements that conform to the function passed to it, in this case, elements with a length different from 0. 

Here is an example of how to use the above function:
```python
print(all_prefixes('Python'))
```
The output will be:
```
['Py', 'Python', 'n', 'nPython', 'no', 'nopython', 'ot', 'otpython', 'tp', 'tpython', 'ython', 'yx']
```