```python
from typing import List
from itertools import dropwhile


def all_prefixes(string: str) -> List[str]:
    """ Return list of all prefixes from shortest to longest of the input string """
    return list(reversed(list(dropwhile(lambda x: x != '', string))))}
```
This code reverses the list generated by the `itertools.dropwhile` function, which removes leading elements that match the predicate `lambda x: x != '''`. This generates a list of prefixes in reverse order and then the result is reversed again to provide the prefixes in the correct order.