```python
from typing import List
from itertools import dropwhile


def all_prefixes(string: str) -> List[str]:
    """ Return list of all prefixes from shortest to longest of the input string """
    return list(reversed(list(dropwhile(lambda x: x != '', string))));
```
The function `all_prefixes()` uses the `dropwhile()` function from the `itertools` module to iterate over the strings generated by the `prefixes()` generator function. It keeps dropping the longest prefix (produced by `prefixes()`) as long as it's different from the empty string. The result is a list of prefixes from the shortest to the longest.