```python
from typing import List
from itertools import dropwhile


def all_prefixes(string: str) -> List[str]:
    """ Return list of all prefixes from shortest to longest of the input string """
    return list(reversed(list(dropwhile(lambda x: x != '', string))))}
```
This code reverses the list generated by the `itertools.dropwhile` function, ensuring that the prefixes are sorted in ascending order - from the shortest prefix, which is the empty string, to the longest possible prefix of the input string. 
The `dropwhile` function itself filters list elements that match a condition, in this case, elements that aren't equal to the empty string, effectively giving us a list of prefixes.