```python
from typing import List
from itertools import dropwhile


def all_prefixes(string: str) -> List[str]:
    """ Return list of all prefixes from shortest to longest of the input string """
    return list(reversed(list(dropwhile(lambda x: x != '', string))));
```
The above code reverses the list generated by the `dropwhile` function so that the prefixes are arranged in order of decreasing length. 
Also, note that this code assumes that the input string contains only letters, and if this assumption is violated, the function might return incorrect results.

Here is a snippet of a corresponding unit test:
```python
def test_all_prefixes():
    assert all_prefixes("abc") == ["a", "ab", "abc"]
    assert all_prefixes("empty") == []
```