```python
from typing import List
from itertools import dropwhile


def all_prefixes(string: str) -> List[str]:
    """ Return list of all prefixes from shortest to longest of the input string """
    return list(reversed(list(dropwhile(lambda x: x != '', string))));
```
The above code reverses the list generated by the `dropwhile` function so that the prefixes are arranged in the correct order (from shortest to longest).

The `dropwhile` function drops elements from the iterable as long as the predicate returns `True`. In this case, we pass an empty string to drop all characters from the input string as long as they are not the empty string. The reversed list is then returned, containing all prefixes from the input string in descending order.