```python
from typing import List
from itertools import dropwhile


def all_prefixes(string: str) -> List[str]:
    """ Return list of all prefixes from shortest to longest of the input string """
    return list(reversed(list(dropwhile(lambda x: x != '', string))))}
```
This code reverses the list generated by the `itertools.dropwhile` function, ensuring that the prefixes are sorted in ascending order, achieving the desired result.

The `dropwhile` function begins with the iterator `string`, producing an iterable by repeatedly moving past elements that satisfy the `lambda` function (`x != ''`). This effectively removes trailing empty strings from the iterable. The reversed version of this filtered iterable is then converted to a list and returned as the solution.