```python
from typing import List
from itertools import dropwhile


def all_prefixes(string: str) -> List[str]:
    """ Return list of all prefixes from shortest to longest of the input string """
    return list(reversed(list(dropwhile(lambda x: x != '', string))))}
```
This code reverses the list generated by the `itertools.dropwhile` function, which sequentially drops elements from the given iterable as long as the predicate returns True.

The overall goal is to generate a list of prefixes from the input string, where each element in the list is a prefix of the next one, eventually reaching the empty string. The reversed list guarantees the correct order from longest to shortest.

To make the function more readable and provide better documentation, you can consider adding type hints and a docstring as done in the original prompt example.