```python
from typing import List
from itertools import dropwhile


def all_prefixes(string: str) -> List[str]:
    """ Return list of all prefixes from shortest to longest of the input string """
    return list(reversed(list(dropwhile(lambda x: x != '', string))));
```
The above code reverses the list generated by the `dropwhile` function so that the prefixes are arranged in the correct order (from shortest to longest). 
It then returns the list of prefixes.