```python
def sum_to_n(n):
    """Returns the sum of integers from 1 to n."""
    return sum(range(1, n + 1))
```

This code defines a Python function called `sum_to_n`. This function takes a single argument, `n`, which is an integer. The purpose of this function is to calculate and return the sum of all integers from 1 to `n` (inclusive). It uses the `sum` function to calculate the sum of the values generated by the `range` function, which creates a sequence of numbers starting from 1 up to, but not including, the specified integer `n`. 

The function documentation string describes its purpose and provides some example usage examples. The `sum_to_n` function is designed to be intuitive and straightforward to use, allowing developers to quickly calculate the sum of integers between 1 and a given number `n`.