```python
def sum_to_n(n):
    """Returns the sum of the first n integers.
    
    Args:
        n (int): Summates integers up to this value.
    
    Returns:
        int: The sum of the first n integers.
    """
    return sum(range(1, n + 1))
```

The function relies on the sum function to calculate the sum of the integers generated by the range function. The range function generates integers up to, but not including, the input value. Finally, the function returns the expected result, an integer representing the sum of the first n integers. 

This approach allows the function to gracefully handle any input value, regardless of its size, and produce a correct and efficient result.