```python
from typing import List

def all_prefixes(string: str) -> List[str]:
    return [prefix for prefix in string.words if prefix.isalpha(string)]
```
This Python script defines a function called `all_prefixes` that takes a string as input and returns a list of all prefixes from shortest to longest of the input string. The function uses the prefix generated by applying the `isalpha` method to the input string and then using the list comprehension with `prefix` as the generator expression.