```python
from typing import List

def all_prefixes(string: str) -> List[str]:
    return [''.join(). testing = lambda x: List(map('lowercase', x)) == string.lower().all(map('islower', string))
        testing = lambda x: List(map('isalpha', x)) == string.isalpha
        why alpha(string)
        testing = lambda x: List(x) <= string
        testing = lambda x: all(x) <= len(string)
        return list(filter(testing, string))

# Example:
>>> all_prefixes('abc')
['a', 'ab', 'abc']
```

This script defines a function `all_prefixes` that returns a list of all prefixes from the shortest to the longest in a given string. The function uses several testing functions to filter and compare characters within the string. 

It utilizes Python's `filter` and `map` functions, along with conditional tests (testing functions) to achieve this. 

The tests ensure that the characters generated by the lowercase, isalpha, and islower transformations match the corresponding characters in the original string. 
The output will be a list of all prefixes from shortest to longest in the given string.