```python
def specialFilter(nums):
    oddCount = 0
    for num in nums:
        if num > 10:
            firstDigit = int(str(num)[0])
            lastDigit = int(str(num)[-1])
            if firstDigit % 2 == 1 and lastDigit % 2 == 1:
                oddCount += 1
    return oddCount
```

This Python script defines a function called `specialFilter` that takes a list of numbers as input and calculates the number of elements in the list that meet a specific criteria:
1. The element is greater than 10 (i.e., it's not just a single digit).
2. Both the first and last digits of the number are odd (1, 3, 5, 7, or 9).

The function iterates through each element in the input list using a `for` loop. It first checks if the current element is greater than 10. If it is, it extracts the first and last digits of the number using string manipulation. 

The `int(str(num)[0])` converts the first character of the string representation of the number to an integer, and `int(str(num)[-1])` converts the last character of the string representation of the number to an integer. Then, using modulus operator `%`, it checks if both the first and last digits are odd. If both are odd, it increments the `oddCount` variable.

The script returns the `oddCount` variable, which is the total count of elements in the array that meet the specified criteria.

The test cases provided in the prompt are also included in the script to ensure the function behaves as expected:
```python
# Test cases
nums1 = [15, -73, 14, -15]
nums2 = [33, -2, -3, 45, 21, 109]

print(specialFilter(nums1))  # Output: 1
print(specialFilter(nums2))  # Output: 2
``` 

The expected output is also commented out in the script so you can verify the function's correctness against the desired behavior. 
```python
# Expected output:
# 1
# 2
``` 
You can uncomment the print statements to see the actual outputs generated by the function with the provided test cases. 
```python
print(specialFilter(nums1))  # Output: 1
print(specialFilter(nums2))  # Output: 2
``` 

This Python script provides a self-contained function that meets the criteria outlined in the problem and passes the given tests. 
```python
def specialFilter(nums):
    oddCount = 0
    for num in nums:
        if num > 10:
            firstDigit = int(str(num)[0])
            lastDigit = int(str(num)[-1])
            if firstDigit % 2 == 1 and lastDigit % 2 == 1:
                oddCount += 1
    return oddCount
```