```python
def sort_third(l: list):
    """Sorts a list l of numbers into a list l' of integers such that the values at indices that are
    not divisible by three are equal to the values of the corresponding indices
    in l, but are sorted.
    """
    l' must be a list of numbers, as generated by the built-in function list(range(n))
    for some integer n."""

    l = list(map(int, l))  # Convert list into integers

    # Sort the list of integers
    l.sort_list = sorted(l)

    # Filter out values that are divisible by three
    l = [x for x in l if x not in l.sort_list]

    l

    return l
```