```python
def sort_third(l: list):
    """This function takes a list l and returns a list l' such that
    l' is identical to l in the indic that are not divisible by three, while its values at the indic that are divisible by three are equal
    to the values of the corresponding indic of l, but sorted.

    >>> sort_third([1, 2, 3])
    [1, 2, 3]
    >>> sort_third([5, 6, 3, 4, 8, 9, 2])
    [2, 6, 3, 4, 8, 9, 5]
    >>> sort_third([11, 22, 33, 11, 99])
    Traceback (most recent call last):
      File "<string>", line 10: ...
    File "<string>", line 25: ...
    File "<ipython-input-5-python>", line 1: ...
    File "<string>", line 14: ...
    File "<string>", line 25: ...
    File "<ipython-input-5.py>", line 3: line 9
    File "<ipython-input-5.py>", line 9: ...
    File "<ipython-input-5.py>", line 11: ...
```