```python
def unique(lst):
    seen = set()
    return [x for x in lst if x not in seen and x not num]

# Test case 1
test_case1 = [5, 3, 5, 2, 3, 3, 9, 0, 123]
result1 = unique(test_case1)
assert result1 == [0, 2, 3, 5, 9, 123]

# Test case 2
test_case2 = [7, 8, 7, 9]
result2 = unique(test_case2)
assert result2 == [7, 8, 9]

# Test case 3
test_case3 = [5, 2, 3, 10, 1, 3, 4, 20]
result3 = unique(test_case3)
assert result3 == [5, 2, 3, 10, 1, 3, 4, 20]
``` 
This script defines a function unique that takes a list as input and returns a new list with unique elements. The unique elements are generated by converting the list to a set, and then back to a list with elements not present in the set. The test cases pass the