```python
def string_sequence(n: int) -> str:
    return f"0 {n}" * (n + 1)

# Test case 1: Verify function with zero input
assertEqual(string_sequence(0), '0')

# Test case 2: Verify function with positive input
assertEqual(string_sequence(5), '0 5 10 15 20 25')

# Test case 3: Verify function with negative input
assertEqual(string_sequence(-5), '0 0 0 0 0')
```
This code defines a function `string_sequence` that generates a string containing space-separated numbers from 0 up to a given positive integer `n`, it uses a simple mathematical formula to achieve this, and the output is generated by string concatenation of repeated "0"s with the provided number. The test cases verify the new function by checking if the output matches the expected result for different input values.