```python
from typing import List

def all_prefixes(string: str) -> List[str]:
    """
    Return list of all prefixes from shortest to longest of the input string
    
    Args:
    string (str): The input string
    
    Returns:
    List[str]: A list of all prefixes in the input string, from shortest to longest.
    
    Example:
    >>> all_prefixes('abc')
    ['a', 'ab', 'abc']
    """
    prefixes = []
    for i in range(1, len(string) + 1):
        prefixes.append(string[:i])
    return prefixes

# Test the function
print(all_prefixes('abc'))
print(all_prefixes('hello'))
print(all_prefixes('xyz'))
```

This script defines a function `all_prefixes` that takes a string as input and returns a list of all prefixes of the string, from shortest to longest. The prefixes are generated by slicing the input string from the beginning up to each possible position, and the resulting list is returned.

When you run this script, it will print the list of prefixes for the strings 'abc', 'hello', and 'xyz'. The output will be:

```python
['a', 'ab', 'abc']
['h', 'he', 'hel', 'hell', 'hello']
['x', 'xy', 'xyz']
```