```python
from typing import List

def all_prefixes(string: str) -> List[str]:
    """
    Return list of all prefixes from shortest to longest of the input string.
    
    Args:
    string (str): The input string.
    
    Returns:
    List[str]: A list of all prefixes in the input string.
    
    Examples:
    >>> all_prefixes('abc')
    ['a', 'ab', 'abc']
    """
    prefixes = []  # Initialize an empty list to store all prefixes
    for i in range(1, len(string) + 1):  # Iterate over the length of the string
        prefixes.append(string[:i])  # Append the prefix of the current length to the list
    
    return prefixes  # Return the list of prefixes

# Test the function
print(all_prefixes('abc'))  # Output: ['a', 'ab', 'abc']
print(all_prefixes('hello'))  # Output: ['h', 'he', 'hel', 'hell', 'hello']
```

This script defines a function `all_prefixes` that generates all prefixes of a given string. The prefixes are generated by iterating over the length of the string and appending each prefix to a list. The function returns this list of prefixes. The script also includes docstrings and test cases to demonstrate its usage.