```python
from typing import List


def all_prefixes(string: str) -> List[str]:
    """
    Return list of all prefixes from shortest to longest of the input string.

    Args:
        string (str): The input string.

    Returns:
        List[str]: A list of all prefixes.

    Example:
        >>> all_prefixes('abc')
        ['a', 'ab', 'abc']
    """
    return [string[i:] for i in range(len(string) + 1)]


# Test the function
print(all_prefixes('abc'))
```

This script defines a function `all_prefixes` that generates a list of all prefixes of the input string. The prefixes are generated by slicing the string from the current index to the end, for all possible indices from 0 to the length of the string (inclusive). The result is a list of strings where each string is a prefix of the input string. The list is sorted from shortest to longest prefix.