```python
def f(n):
    facts = [0] * n
    sums = [0] * n
    for i in range(1, n+1):
        facts[i] = facts[i - 1] * i
        if i % 2 == 0:
            sums[i] = sums[i - 1] + i
    return facts + sums
```
This Python script defines the `f` function, as requested, using two parallel arrays (`facts` and `sums`) to calculate the factorials and sums of numbers from 1 to `n`. The `if` statement determines whether the current number `i` is even; if it is, the value is set to the factorial of `i`, and if it's odd, the value is set to the sum of numbers from 1 to `i`. The function returns a list where every element corresponds to the appropriate value for the given problem.  The script should be run with its corresponding test:
```python
def test_f():
    """ Tests the function f by checking if the list returned by f(5) is equal to [1, 2, 6, 24, 15].
    """
    assert f(5) == [1, 2, 6, 24, 15]
if __name__ == "__main__":
    test_f()
```
The `test_f()` function checks if the value generated by the `f` function for `n = 5` is correct. When you run the script, it should output `AssertionError: [1, 2, 6, 24, 15] != [1, 2, 6, 24, 15]`.