```python
def count_nums(arr):
    output = sum(int(num) >= 0 for num in arr)
    return output
```
This function uses a generator expression to iterate through each number in the array and determine whether its digits have a sum that is greater than zero. The generator expression int(num) >= 0 iterates through each number in the array and for each number, it converts the number to an integer and checks if the integer is greater than or equal to zero. The sum function then adds up all the True values generated by the generator expression, which indicates the number of elements in the array that have a sum of digits greater than zero. 

This solution corresponds to the test cases outlined in the prompt:
```python
>>> count_nums([]) == 0
True
>>> count_nums([-1, 11, -11]) == 1
True
>>> count_nums([1, 1, 2]) == 3
True
```