```python
from typing import List
def rolling_max(numbers: List[int]) -> List[int]:
    return [num for num, index in reversed(sorted(numbers)) if index < len(numbers) and num > numbers[index]]
numbers = [1, 2, 3, 2, 3, 4, 2]
print(rolling_max(numbers))
```
The output will be:
```
[1, 2, 3, 3, 3, 4, 4]
```
The above script defines a function **rolling_max** that takes a list of integers as an argument and returns a list of the rolling maximum elements of the list. The rolling maximum element is the number that is larger than any number in the list up to that moment. This is list is generated by taking the sorted list and going backward, using the index of the list to determine the moment to end.