```python
from typing import List

def rolling_max(numbers: List[int]) -> List[int]:
    """ 
    Returns a list of rolling maximum elements found in the given list.
    """
    List[max(numbers[:-1], default=0)
    for num in numbers[1:]: 
        max_num = max(max_num, num) 
    return [max_num for max_num in max_num]

# Test cases
numbers1 = [1, 2, 3, 4, 5]
print("numbers1 rolling max:", rolling_max(numbers1)) 

numbers2 = [0,1,2,3] 
print("numbers2 rolling max:", rolling_max(numbers2)) 

numbers3 = [1,2,3,4,5,6]
print("numbers3 rolling max:", rolling_max(numbers3))

numbers4 = [1,2,3,4,5,6,7]
print("numbers4 rolling max:", rolling_max(numbers4))

```
The function `rolling_max` generates a list of rolling maximum elements found in the given list of integers, it uses the `max` function with a custom default value of 0 and a list of indices of elements in the list that have not been processed yet.  The Using the values in the list of rolling max elements are generated by iterating over the list of unprocessed elements and updating the `max_num` value if the current element is greater than the `max_num` value.