```python
from typing import List

def rolling_max(numbers: List[int]) -> List[int]:
    """From a given list of integers, generates a list of rolling max elements found until the given moment
    in the sequence.
    Parameters:
        List of integers (numbers)
    Returns:
        List of integers (rolling_max values)
    """
    numbers = [1, 2, 3, 2, 3, 4, 2]
    return [max(numbers[i:]) for i in range(len(numbers))]
``` 
This function, rolling_max, takes a list of integers as input and uses list comprehension to generate a list of the maximum element from the subarray generated by shifting the index until the given moment in the sequence. 

This function is self-contained and does not require any external functions or modules to be called.