```python
def flip_case(string: str) -> str:
    """
    For a given string, flip lowercase characters to uppercase and uppercase to lowercase.
    
    Args:
    string (str): The input string.
    
    Returns:
    str: The input string with case flipped.
    
    Example:
    >>> flip_case('Hello')
    'hELLO'
    """
    return ''.join(char.upper() if char.islower() else char.lower() for char in string)
```

Let's break down this script:

- We define a function `flip_case` that takes a string `string` as input and returns a string.
- The function uses a generator expression to iterate over each character `char` in the string.
- For each character, it checks if it's lowercase using `char.islower()`. If it is, we convert it to uppercase using `char.upper()`.
- If the character is not lowercase (i.e., it's uppercase), we do nothing and the `char` itself is used in the result string.
- The `''.join(...)` call is used to concatenate all the characters generated by the generator expression into a single string.
- Finally, we return the resulting string with the case flipped.