
def int_to_mini_roman(number):
    """
    Given a positive integer, obtain its roman numeral equivalent as a string,
    and return it in lowercase.
    Restrictions: 1 <= num <= 1000

    Examples:
    >>> int_to_mini_roman(19) == 'xix'
    >>> int_to_mini_roman(152) == 'clii'
    >>> int_to_mini_roman(426) == 'cdxxvi'
    """
    circular_roman_numerals_dict = {
        1: 'x',
        2: 'xx',
        3: 'xxx',
        4: 'xxxx',
        5: 'xl',
        6: 'lx',
        7: 'll',
        8: 'llx',
        9: 'lxx',
        10: 'lxxx',
        11: 'lxxxx',
        12: 'il',
        13: 'ilx',
        14: 'ilxx',
        15: 'ilxxx',
        16: 'ilxxxx',
        17: 'ii',
        18: 'iiil',
        19: 'iiix',
        20: 'iiixx',
        21: 'iiili',
        22: 'iiill',
        23: 'iiillx',
        24: 'iiillxx',
        25: 'iiillxxxx',
        26: 'v',
        27: 'vii',
        28: 'viii',
        29: 'vix',
        30: 'vxx',
        31: 'vxxx',
        32: 'vxxxx',
        33: 'vi',
        34: 'vii',
        35: 'viii',
        36: 'vix',
        37: 'vxx',
        38: 'vxxx',
        39: 'vxxxx',
        40: 'ix',
        41: 'xi',
        42: 'xii',
        43: 'xiii',
        44: 'xix',
        45: 'xv',
        46: 'xvi',
        47: 'xvii',
        48: 'xviii',
        49: 'xix',
        50: 'xv',
        51: 'xvi',
        52: 'xvii',
        53: 'xviii',
        54: 'xix',
        55: 'xv',
        56: 'xvi',
        57: 'xvii',
        58: 'xviii',
        59: 'xix',
        60: 'xv',
        61: 'xvi',
        62: 'xvii',
        63